name: CI - Security Checks

on:
  push:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep (custom rule)
        uses: returntocorp/semgrep-action@v1
        with:
          config: semgrep/semgrep.yml

  # (اختیاری) اجرای تست‌های ساده پایتون برای حرفه‌ای‌تر شدن
  tests:
    runs-on: ubuntu-latest
    needs: semgrep   # اول Semgrep، بعد تست‌ها
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # فعلاً وابستگی خاصی نداریم؛ اگر اضافه شد اینجا نصب کن
          echo "no extra deps"
      
      - name: Run tests
        run: |
          python -m tests.test_app
